return {
    "status":{
       "code":"HYD-82-000",
       "vnMessage":"Thành công.",
       "enMessage":"Success."
    },
    "contracts":[
       {
          "ewalletId":"423",
          "provider":{
             "name":"Momo",
             "img":"api/contentservices/api/contentstream-id/contentRepository/234-08eca11f0ebe?_=23423"
          },
          "acctName":"TAN",
          "acctNo":"23423",
          "acctBalance":"23",
          "username":"TAN",
          "currency":"VND",
          "linkType":"ACCOUNT"
       },
       {
          "ewalletId":"43",
          "provider":{
             "name":"AirPay",
             "img":"api/contentservices/api/contentstream-id/contentRepository/2342?_=423"
          },
          "acctName":"TAN",
          "acctNo":"34",
          "acctBalance":"32",
          "username":"TAN",
          "currency":"VND",
          "linkType":"ACCOUNT"
       },
       {
          "ewalletId":"4234",
          "provider":{
             "name":"ZaloPay",
             "img":"api/contentservices/api/contentstream-id/contentRepository/43?_=423"
          },
          "acctName":"TAN",
          "acctNo":"23423",
          "acctBalance":"423",
          "username":"TAN",
          "currency":"VND",
          "linkType":"CARD",
          "cardNumber":"92343423xx0461"
       }
    ]
 };